default: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *defaults
  adapter: postgresql
  database: streaming_dev

staging:
  <<: *defaults
  adapter: postgresql
  database: streaming_stag

test:
  <<: *defaults
  adapter: postgresql
  database: streaming_test

production:
  <<: *defaults
  adapter: postgresql
  database: streaming_prod